### ISSUE TITLE
Crash when being killed with enchanted yoyo

### ISSUE THREAD

**Issue by darkphan** [Jozufozu/Yoyos#1]
When someone on a server kills someone else with an enchanted yoyo, the person that was killed will crash with the following error:
``
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at com.jozufozu.yoyos.common.EntityYoyo.getPlayerHandPos(EntityYoyo.java:336)
	at com.jozufozu.yoyos.client.RenderYoYo.doRender(RenderYoYo.java:48)
	at com.jozufozu.yoyos.client.RenderYoYo.func_76986_a(RenderYoYo.java:25)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:624)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Jozufozu** [comment]
Fairly certain this has been fixed
